### ISSUE TITLE
react-loadable不兼容，主要是第一次访问，取到的dom是不对的

### ISSUE THREAD

**Issue by cgx9** [fi3ework/react-live-route#11]
当使用react-loadable时，第一次点击，当前页并不会隐藏（第二页会显示在当前页的下方），第二次及后面点击才生效。

**Comment by fi3ework** [comment]
react-loadable 去包的哪个组件呢？列表页还是详情页？

**Comment by cgx9** [comment]
都包，但是在列表页时，第一次访问，比如刷新，我跟踪代码，` ReactDOM.findDOMNode(this)`这个this不对。所以取到的dom不对。你可以去复现出来。

**Comment by Vibing** [comment]
@cgx9 

你可以在组件外面包一个`div`试一试：
```jsx
const List = loadable({
  loader: () => import('./pages/list'),
  loading: () => <div>loading...</div>
});

<LiveRoute exact path="/list" livePath="/list/:id">
  <div>
    <List />
  </div>
</LiveRoute>
```

**Comment by fi3ework** [comment]
Closed, https://github.com/fi3ework/react-live-route#ensuredidmount
