### ISSUE TITLE
react-router-dom4.3.1不能实现缓存效果

### ISSUE THREAD

**Issue by whyjson** [fi3ework/react-live-route#15]
我在react-router-dom4.3.1版本使用改插件 不能实现缓存的效果。

**Comment by fi3ework** [comment]
可以给个使用的 demo 或最简代码吗

**Comment by whyjson** [comment]
`

> ![default](https://user-images.githubusercontent.com/26684053/53403449-a6814480-39ee-11e9-8881-b72ee09dcd8f.png)

`

**Comment by fi3ework** [comment]
will chrck it later

**Comment by whyjson** [comment]
你这轮子就是在跳转路由得时候组件不卸载吗？

**Comment by fi3ework** [comment]
@whyjson 
是的，但是如果 LiveRoute 这个路由的父路由被卸载了那么还是会被卸载，这是 React 的分形机制决定的。

**Comment by fi3ework** [comment]
works fine with react-router-dom 4.3.1, see [demo](https://codesandbox.io/s/yj9j33pw4j). Could not be reproduced.
