### ISSUE TITLE
安卓5.1不支持range.includes等新语法

### ISSUE THREAD

**Issue by Vibing** [fi3ework/react-live-route#18]
希望可以对老版本系统语法兼容一下，感谢！！

**Comment by fi3ework** [comment]
没打 polyfill 吗 @Vibing

**Comment by Vibing** [comment]
@fi3ework 我使用了`exclude: /node_modules/`。我想编译node_modules里的react-live-route，使用了(webpack-node-externals)[https://github.com/liady/webpack-node-externals],但那个包会报错，解决不了这个问题。
我可能需要的是如何只编译node_modules里的某些包(比如react-live-route)，其他包被exclude掉。所以我还没找到方法

**Comment by fi3ework** [comment]
resolved in https://github.com/fi3ework/react-live-route/commit/04f769e7304344f02a8961c359822070ed94a337
