### ISSUE TITLE
如果A页面很长,那么跳转到B页面时,滚动条并非在顶部

### ISSUE THREAD

**Issue by sin911** [fi3ework/react-live-route#24]
如果A页面有3个屏幕高度,然后跳转到B页面的链接恰好也在页面最后
`<br />比如A页面很长很长<br /><br /><br /><br />这个是在页面底部的链接<Link to="/b" >---去B页面---</Link>`
如上代码,那么显示B页面时(恰好B页面也很长很长),滚动条并非在顶部,所以问题就是:B页面的滚动条有办法一开始就在顶部吗?

还有一个疑问是,这个插件支持延迟加载组件吗?就是React.lazy搭配Suspense
我发现用了延迟加载的话,第一次后退不会有display:none,要第2次才会display:none

**Comment by fi3ework** [comment]
1. 第一个问题，这是似乎是浏览器的一个滚动机制，暂时只能手动置顶一下。
2. 支持，但是需要额外做一点工作，可以参考：https://github.com/fi3ework/react-live-route#ensuredidmount

**Comment by sin911** [comment]
this.props.ensureDidMount()方法是不是与react-loadable有关?
因为我没用react-loadable,而是用了react自带的React.lazy,所以在调用ensureDidMount方法时,显示未定义.

**Comment by fi3ework** [comment]
1. 无关
2. 是最新版本吗吗，然后可以贴一下调用 ensureDidMount 这部分的代码吗

**Comment by sin911** [comment]
定义路由时,用的render方法
![定义路由](http://pv2rpdhju.bkt.clouddn.com/111111111.png)

然后用了 React.lazy包裹
![使用方法](http://pv2rpdhju.bkt.clouddn.com/222222.png)

结果找不到ensureDidMount 
![报错了](http://pv2rpdhju.bkt.clouddn.com/33333333.png)

**Comment by fi3ework** [comment]
see #25
