### ISSUE TITLE
Do not support typescript?

### ISSUE THREAD

**Issue by saifeiLee** [fi3ework/react-live-route#28]
I want to use this component in Typescript/React project.

**Comment by fi3ework** [comment]
It supports TypeScript as it's written in TypeScript.

**Comment by cixiu** [comment]
@fi3ework npm包里的package.json文件中有`types: lib/index.d.ts`配置，但是lib文件下并没有index.d.ts文件

**Comment by fi3ework** [comment]
fixed in 3.1.6 😥
