### ISSUE TITLE
LiveRoute 渲染的组件异步 re-mount 导致标记的 DOM 失效

### ISSUE THREAD

**Issue by picnic-yu** [fi3ework/react-live-route#3]
支持在ty里面使用吗

**Comment by fi3ework** [comment]
支持的啊，ts 是兼容 js 的

**Comment by jaydenxiao2016** [comment]
您好，如何在三层界面使用livepath，比如搜索条件一个界面，点击确定后到列表一个界面，然后点击列表item到详情界面，从详情界面回退时列表和搜索界面都还在

**Comment by fi3ework** [comment]
livePath 也可以接受一个由上述规则的 string 类型对象组成的数组，如果数组中的任意一个 string 匹配则 livePath 匹配。

**Comment by jaydenxiao2016** [comment]
` {/*案件查询*/}
                    <LiveRoute
                        path={RoutePath.CaseSearchPage} component={CaseSearchPage}
                        livePath={[RoutePath.CaseListPage,RoutePath.CaseInfoPage]}
                    />
                    <LiveRoute
                        path={RoutePath.CaseListPage} component={CaseListPage}
                        livePath={[RoutePath.CaseInfoPage]}
                    />
                    <Route path={RoutePath.CaseInfoPage} component={CaseInfoPage}/>`
在第二界面点击到第三个界面的时候发现，第一次跳转会发现一个奇怪的现象，第三个界面跑到第二个界面的下方了，这种使用方法是正确的吗

**Comment by fi3ework** [comment]
听你这么描述的话，我觉得会不会是第二个界面就是 CaseListPage 有内联的样式，比如 `display: block`，这样覆盖了 LiveRoute 对它的 `display: none`

**Comment by jaydenxiao2016** [comment]
但点击第二次后都是正常的了，应该不会有这可能吧

**Comment by fi3ework** [comment]
就是你从2进3的时候第一次不正常，然后返回2再进3 就正常了是吧

**Comment by jaydenxiao2016** [comment]
嗯，是的

**Comment by fi3ework** [comment]
我晚上写个小 demo 测试一下

**Comment by jaydenxiao2016** [comment]
好的，非常感谢

**Comment by jaydenxiao2016** [comment]
我发现是正常的组件没问题的，就那个第二个组件我是封装了一层状态组件，所以出问题了，但正常Route是没问题的，用liveRoute就出现这个问题了
`
/**
 * 请求网络数据组件（根据结果显示不同状态界面）
 * @param path
 * @param params
 * @returns {Function}
 * @constructor
 */
export let NetDataComponent = (path, params = {}) => {
    return (ViewComponent) => {
        return class componentName extends Component {
            constructor(props) {
                super(props);
                this.state = {
                    data: {},
                    status: 1,//1:loading 2:错误 3：空 4:展示内容
                    message: "",//信息
                };
                this.isUnMount = false;
            }

            componentDidMount() {
                // 找到请求的方法
                console.log(path)
                // 声明变量存一下参数params
                let p = params;
                // 如果params是函数，给函数传入props，上面有match history location
                // 函数要返回一个对象，对象就是发送给后端的参数
                if (typeof params === 'function') {
                    p = params(this.props)
                }
                let lastStatus;
                let lastMessage;
                BaseNetModel.postJSON(path, JSON.stringify(p)).then((data) => {
                    if (!this.isUnMount) {
                        //成功
                        if (data.flag === 1) {
                            //是数组
                            if (data.data instanceof Array) {
                                if (data.data.length > 0) {
                                    lastStatus = 4;
                                } else {
                                    lastStatus = 3;
                                }
                            }
                            //是否是空对象
                            else if (!EmptyUtils.isEmptyObject(data.data)) {
                                lastStatus = 4;
                            } else {
                                lastStatus = 3;
                            }
                        } else {
                            lastStatus = 2;
                        }
                        this.setState({
                            data,
                            status: lastStatus,
                            message: lastMessage,
                        })
                    }
                }).catch((error) => {
                    lastStatus = 2;
                    lastMessage = error;
                    this.setState({
                        status: lastStatus,
                        message: lastMessage,
                    })
                });

            }

            componentWillUnmount() {
                // 当卸载时候设置一个标示，在ajax回来时候不触发setState
                this.isUnMount = true;
            }

            renderStatusView = () => {
                switch (this.state.status) {
                    case 1:
                        return <LoadingComponent/>;
                    case 2:
                        return <ErrorComponent title="错误信息"
                                               message={this.state.message ? this.state.message.toString() : "数据访问错误"} {...this.props}/>;
                    case 3:
                        return <EmptyComponent title="数据为空" message="暂无数据" {...this.props}/>;
                    default:
                        return <ViewComponent responseData={this.state.data} {...this.props}/>;
                }
            }

            render() {
                return this.renderStatusView()
            }
        }
    }
}





`

**Comment by jaydenxiao2016** [comment]
第二个组件是这样访问的
`
export default NetDataComponent(Constants.allPath.caseSearchPath, function (props) {
    return props.location.state;
})(CaseListPage);
`

**Comment by fi3ework** [comment]
大概看了下，应该是这样的：
不套 `NetDataComponent` 的第 2 页的 LiveRoute 是正常工作的对吧。
套了 `NetDataComponent` 的第 2 页的问题在于 Route 或者 LiveRoute 渲染时标记的那个 DOM 在你异步获取完数据之后然后整个组件 re-mount 所以被修改了，这也是为什么第二次是没问题的（因为已经异步结束了）。
确实没考虑过这个问题，我想下怎么处理。
可以先给你一个粗暴的解决方案：将

```jsx
            render() {
                return this.renderStatusView()
            }
```

改为

```jsx
            render() {
                return <div>{this.renderStatusView()}</div>
            }
```

这样不会 re-mount，可以先试下。

**Comment by jaydenxiao2016** [comment]
非常感谢，入门react一段时间了，以后有事可以请教一下大神，可以加一个QQ吗，我QQ791830569
