### ISSUE TITLE
页面加载问题

### ISSUE THREAD

**Issue by tangMr1234** [fi3ework/react-live-route#31]
我有A/B/C三页，首次进入加载A页，点击切换到B页时，A页不会隐藏，B页显示在A页下方，接着打开C页，C页会显示在B页下方；重新再点击一次A/B/c页后会恢复正常，求解这是什么原因，已使用this.props.ensureDidMount()

**Comment by tangMr1234** [comment]
使用的React.lazy加载的路由

**Comment by tangMr1234** [comment]
应该说每次打开一个新的页面，之前打开过的页面，display：none都会被清除，全部显示出来，只有在挨个点一遍才会重新隐藏

**Comment by tangMr1234** [comment]
好吧，没看仔细，原来要用Suspense；还是缺少文档

**Comment by fi3ework** [comment]
@tangMr1234 上一下路由那块的代码吧，这样说很难理解..

**Comment by tangMr1234** [comment]
@fi3ework 感谢回复，已经好了，是我写错了，忘记关闭问题了，谢谢
