### ISSUE TITLE
是否能把路由的隐藏改一下，display:none=>visibility: hidden;这样会有什么影响

### ISSUE THREAD

**Issue by ReactLearningTrip** [fi3ework/react-live-route#33]
![image](https://user-images.githubusercontent.com/20716305/70489130-c2954300-1b35-11ea-9e6a-217d327301bb.png)
我需要在多页面切换时，计算整体高度，来算出table  scroll的高度，但是我需要拿到页面每一个元素的高度，但是由于切换导致路由display：none了，所以拿不到将要切换的页面元素高度，所以想改成visibility: hidden；但是想知道您用display:none而不用visibility: hidden出于什么考虑

**Comment by fi3ework** [comment]
@ReactLearningTrip 不能，因为 `visibility: hidden` 只是将元素变为「不可见」，实际上元素占据的布局还是在的，这样无法做到隐藏。

**Comment by ReactLearningTrip** [comment]
@fi3ework 但是我的目的就是让他隐藏且占位啊，因为我需要拿到隐藏元素的高度，但是我怕我改成visible，有别的隐患

**Comment by fi3ework** [comment]
不会有别的问题，你可以直接把源代码 copy 一份用在你的项目里

**Comment by ReactLearningTrip** [comment]
我改了之后在npm发布了一个包，可以吗

**Comment by ReactLearningTrip** [comment]
visible有闪屏问题---

**Comment by fi3ework** [comment]
可以随意使用，MIT 协议
