### ISSUE TITLE
its not ‘display:none’ on the old page, when the first pushState.

### ISSUE THREAD

**Issue by destLonY** [fi3ework/react-live-route#36]
first, i open the List view, and the List view route is setting 'keep-alive';
then i enter into Detail view;

the List view is not be ummounted, thats true.
but the List view is not in 'display: none'.
so there are two component on Detail view...

after I goback the List view and enter Detail view again, this problem is not exist(List view is display: none).

**Comment by destLonY** [comment]
Its the react.lazy cause this problems...
LiveRoute can not get the Dom in componentDidMout. so the "display: none" fail in first timing.

**Comment by fi3ework** [comment]
@destLonY take a look at `ensureDidMount` https://github.com/fi3ework/react-live-route#ensuredidmount-code-splitting 🤔
